import ADBKit
import Foundation

/// Wire shapes for the saved deep links, the bug-report zip, and the toolchain
/// check behind Settings ▸ Doctor.
///
/// Three unrelated screens in one file because each is a single route over a
/// service ADBKit already has; a file apiece would be three files that each say
/// one thing.
public enum DiagnosticsProtocol {
    // MARK: - Deep links

    /// One saved link. `id` is generated by whoever adds it and travels back
    /// unchanged, so an edit updates rather than duplicating.
    public struct Link: Codable, Equatable, Sendable {
        public let id: String
        public let label: String
        public let url: String
        /// Epoch millis, as `DeepLink` stores it.
        public let createdAt: Double

        public init(_ link: DeepLink) {
            id = link.id
            label = link.label
            url = link.url
            createdAt = link.createdAt
        }

        public init(id: String, label: String, url: String, createdAt: Double) {
            self.id = id
            self.label = label
            self.url = url
            self.createdAt = createdAt
        }

        var model: DeepLink {
            DeepLink(id: id, label: label, url: url, createdAt: createdAt)
        }
    }

    /// Which app's links, and — for a launch — where to send them.
    ///
    /// **Keyed by package id.** The Mac keys the same on-disk map by *saved
    /// bundle* id, which is a UUID, so entries from the two apps sit in one file
    /// without colliding and without being shared. That is the honest state of
    /// it until this app grows a bundle store of its own; a package id is the
    /// app's real identity either way.
    public struct LinksRequest: Codable, Equatable, Sendable {
        public let packageId: String
        public init(packageId: String) { self.packageId = packageId }
    }

    public struct LinksResponse: Codable, Equatable, Sendable {
        public let links: [Link]
    }

    /// The whole list for one app, written as one value.
    ///
    /// A `PUT`-shaped write rather than add/edit/delete verbs: the client holds
    /// the list it is showing, and three routes would each have to re-derive
    /// what the fourth already knows. `JSONStore.update` makes the swap atomic.
    public struct LinksWriteRequest: Codable, Equatable, Sendable {
        public let packageId: String
        public let links: [Link]

        public init(packageId: String, links: [Link]) {
            self.packageId = packageId
            self.links = links
        }
    }

    public struct LaunchRequest: Codable, Equatable, Sendable {
        public let serials: [String]
        public let url: String

        public init(serials: [String], url: String) {
            self.serials = serials
            self.url = url
        }
    }

    /// One answer per device.
    ///
    /// `InstallProtocol.Outcome` rather than a second identical struct: "what
    /// each device said" is one idea, and two copies of it on the wire would be
    /// two things to keep in agreement for no gain.
    public struct LaunchResponse: Codable, Equatable, Sendable {
        public let outcomes: [InstallProtocol.Outcome]
    }

    // MARK: - Bug report

    public struct BugReportRequest: Codable, Equatable, Sendable {
        public let serial: String
        /// Optional context — the app's version goes in the zip when it is given.
        public let packageId: String?
        /// A **host** folder this process's client chose, as `/v1/files/pull`
        /// takes one. The daemon never decides where a caller's files go.
        public let destination: String

        public init(serial: String, packageId: String? = nil, destination: String) {
            self.serial = serial
            self.packageId = packageId
            self.destination = destination
        }
    }

    public struct BugReportResponse: Codable, Equatable, Sendable {
        /// Where the zip landed, for the Show in folder button.
        public let path: String
    }

    // MARK: - The toolchain

    public struct ToolReport: Codable, Equatable, Sendable {
        /// `Tool`'s raw value — adb, scrcpy, ffmpeg, emulator.
        public let id: String
        public let installed: Bool
        public let path: String?
        public let version: String?
        /// Where to get it. The app never installs a tool itself, on either
        /// platform, so the hint is the whole answer to a missing one.
        public let installHint: String
    }

    public struct ToolsResponse: Codable, Equatable, Sendable {
        public let tools: [ToolReport]
    }

    public static let badLinkRequest = DaemonProtocol.ErrorBody(
        code: "bad_link_request", message: "A deep link needs a package id and a url.")
    public static let badBugReportRequest = DaemonProtocol.ErrorBody(
        code: "bad_bugreport_request",
        message: "A bug report needs a serial and a destination folder.")
}

/// The five diagnostics routes.
enum DiagnosticsRoutes {
    static func linksRead(body: Data, backend: any DaemonBackend) async -> DaemonProtocol.Answer {
        guard let request = try? JSONDecoder().decode(
            DiagnosticsProtocol.LinksRequest.self, from: body), !request.packageId.isEmpty
        else { return (400, DaemonProtocol.encoded(DiagnosticsProtocol.badLinkRequest)) }
        let links = await backend.deepLinks(packageId: request.packageId)
        return (200, DaemonProtocol.encoded(DiagnosticsProtocol.LinksResponse(
            links: links.map(DiagnosticsProtocol.Link.init))))
    }

    static func linksWrite(body: Data, backend: any DaemonBackend) async -> DaemonProtocol.Answer {
        guard let request = try? JSONDecoder().decode(
            DiagnosticsProtocol.LinksWriteRequest.self, from: body), !request.packageId.isEmpty
        else { return (400, DaemonProtocol.encoded(DiagnosticsProtocol.badLinkRequest)) }
        do {
            try await backend.writeDeepLinks(
                packageId: request.packageId, links: request.links.map(\.model))
            return (200, DaemonProtocol.encoded(DiagnosticsProtocol.LinksResponse(
                links: request.links)))
        } catch {
            // The store, not a device: a disk that refuses the write is a
            // daemon-side fault and says so.
            return (500, DaemonProtocol.encoded(DaemonProtocol.ErrorBody(
                code: "store_failed", message: "Could not save the deep links.",
                detail: "\(error)")))
        }
    }

    /// Launches one url on every named device, answering per device.
    ///
    /// Per device because the Mac toasts once per target: three phones where one
    /// has no handler for the scheme is a partial success, not a verdict.
    static func linksLaunch(body: Data, backend: any DaemonBackend) async -> DaemonProtocol.Answer {
        guard let request = try? JSONDecoder().decode(
            DiagnosticsProtocol.LaunchRequest.self, from: body),
            !request.url.isEmpty, !request.serials.isEmpty
        else { return (400, DaemonProtocol.encoded(DiagnosticsProtocol.badLinkRequest)) }
        var outcomes: [InstallProtocol.Outcome] = []
        for serial in request.serials {
            do {
                let result = try await backend.launchDeepLink(serial: serial, url: request.url)
                outcomes.append(InstallProtocol.Outcome(
                    serial: serial, ok: result.ok, message: result.message))
            } catch {
                outcomes.append(InstallProtocol.Outcome(
                    serial: serial, ok: false, message: "\(error)"))
            }
        }
        return (200, DaemonProtocol.encoded(
            DiagnosticsProtocol.LaunchResponse(outcomes: outcomes)))
    }

    static func bugReport(body: Data, backend: any DaemonBackend) async -> DaemonProtocol.Answer {
        guard let request = try? JSONDecoder().decode(
            DiagnosticsProtocol.BugReportRequest.self, from: body),
            !request.serial.isEmpty, !request.destination.isEmpty
        else { return (400, DaemonProtocol.encoded(DiagnosticsProtocol.badBugReportRequest)) }
        do {
            let path = try await backend.createBugReport(
                serial: request.serial, packageId: request.packageId,
                destination: request.destination)
            return (200, DaemonProtocol.encoded(DiagnosticsProtocol.BugReportResponse(path: path)))
        } catch {
            // A device that would not answer, or a host with no archiver: both
            // carry their own words rather than becoming a generic failure.
            return (502, DaemonProtocol.encoded(DaemonProtocol.ErrorBody(
                code: "bugreport_failed", message: "Could not build the bug report.",
                detail: "\(error)")))
        }
    }

    static func tools(backend: any DaemonBackend) async -> DaemonProtocol.Answer {
        let report = await backend.detectTools()
        // Sorted by the enum's own order so the Doctor lists them the same way
        // every time; a dictionary's iteration order is not an order.
        let tools = Tool.allCases.compactMap { tool -> DiagnosticsProtocol.ToolReport? in
            guard let status = report[tool] else { return nil }
            return DiagnosticsProtocol.ToolReport(
                id: tool.rawValue, installed: status.installed, path: status.path,
                version: status.version, installHint: status.installHint)
        }
        return (200, DaemonProtocol.encoded(DiagnosticsProtocol.ToolsResponse(tools: tools)))
    }
}
