import Foundation

extension FeatureRegistry {
    /// Short "what it does and how" notes, surfaced as ⓘ help in the UI.
    /// `role` trims the emulators note to the platform(s) the role can see
    /// (see `presented(_:for:)`); every other note is role-independent.
    public static func howTo(for featureID: String, role: UserRole? = nil) -> String? {
        if featureID == "emulators" {
            switch role {
            case .iosDeveloper:
                return "Your Xcode iOS Simulators in one place: boot or shut them down. "
                    + "Booted ones join the device bar. Simulators need Xcode."
            case .some:
                return "Your Android Studio AVDs in one place: launch normally, cold boot, or "
                    + "wipe data first. Running ones join the device bar. AVDs need the SDK emulator."
            case nil:
                break
            }
        }
        return notes[featureID]
    }

    private static let notes: [String: String] = [
        "send-text": "Types text into whatever field is focused on the device, via `adb shell input text`. Unicode and % need the ADBKeyboard app — you'll be offered a one-click install. Save the text you send often as a named snippet — the list ranks by recent use, and `{clipboard}` / `{ip}` fill in with the live value when inserted.",
        "get-ip": "Reads the device's Wi-Fi IP (wlan0) and copies it — handy for wireless ADB or pointing the device at your local services.",
        "connection": "All the connection plumbing in one place — copy the device's Wi-Fi IP, reverse a port back to your Mac (Metro), drop a wireless connection, set Private DNS, and run the Android 11+ wireless ADB pairing flow. Wi-Fi, Network Speed, and Emulators stay on their own screens.",
        "reverse-port": "Maps a device port back to your Mac (`adb reverse`), so the device reaching localhost:8081 hits YOUR machine — essential for Metro/dev servers over USB.",
        "wireless-adb": "Frees you from the cable. Over USB: one click switches the device to tcpip and connects. Android 11+: use the pairing code flow from Developer options → Wireless debugging.",
        "network-speed": "Watches live download/upload throughput, sampled from `/proc/net/dev` byte counters once a second — device-wide total, a per-interface breakdown (wlan0, cellular…), and a rolling chart. It streams as soon as you open it; hit Record whenever you want to capture a session with totals and export it as JSON + CSV. Device-wide only — per-app traffic needs root on modern Android.",
        "wifi": "Shows the current Wi-Fi connection (SSID, IP, link speed, frequency, signal) from `cmd wifi status`, toggles the radio with `svc wifi`, lists saved networks (`cmd wifi list-networks`), and connects to one (`cmd wifi connect-network`, Android 11+). On a rooted device it also reads saved passwords from WifiConfigStore.xml — connect/password features depend on the ROM allowing it over adb.",
        "private-dns": "Sets the device-wide Private DNS (DNS-over-TLS) mode via `settings put global private_dns_mode` — Off, Automatic (opportunistic), or a specific provider hostname like `dns.google` or `1dot1dot1dot1.cloudflare-dns.com`. Android 9+, no root needed.",
        "system-restrictions": "Dev-time toggles for common Android restrictions. No root: skip ADB-install verification, disable the package verifier, allow hidden-API access (`hidden_api_policy`), keep the screen awake while charging. Root only: SELinux Enforcing↔Permissive (`setenforce`) and remounting the system partition read-write — these only appear when a root shell is available.",
        "react-native": "Everything for React Native debugging in one place — reload the JS bundle, open the dev menu, simulate process death, point the app at a Metro dev server, and launch saved deep links. Reload and Dev Menu need a dev build with the app in front; deep links need a saved bundle; process death targets the selected bundle or the app in front.",
        "open-dev-menu": "Sends keycode 82 — opens the React Native developer menu, same as shaking the device.",
        "reload-js": "Sends R twice (keycode 46 46) to reload the JS bundle. Only works in React Native dev builds.",
        "deep-link": "Saves your app's deep links and launches them — via the system VIEW intent on Android, or `simctl openurl` on an iOS Simulator. Test routing without typing URLs on the device.",
        "process-death": "Backgrounds the app (HOME) then kills its process — reopen it on the device to verify state restoration survives a real process death. Targets the selected bundle, or the app in front when none is chosen.",
        "rn-dev-host": "Points the app at a Metro dev server. localhost reverse-tunnels the port to your Mac; a remote host writes React Native's `debug_http_host` preference via `run-as` (dev builds are debuggable) and relaunches the app — the chosen bundle, or the app in front. Where `run-as` is refused it sets the `metro.host` property (emulators, rooted devices), otherwise the dev menu opens so you can set it by hand.",
        "js-console": "A Chrome-style JavaScript console for your React Native app. It connects to the Hermes debugger that Metro exposes on your Mac — it lists targets at `http://localhost:<port>/json/list` and speaks the Chrome DevTools Protocol over a WebSocket, the same path Chrome DevTools and React Native DevTools use. Type expressions to evaluate them in the running app (with `$_` for the last result), watch `console.log`/`warn`/`error` stream live with filters and search, and expand any logged object. Needs a dev build running Hermes. Metro is usually on 8081, but it varies per app — set the port in the toolbar. For a USB device, tap “adb reverse” so the device can reach Metro.",
        "reactotron": "A Reactotron server built right in — no separate desktop app. Droidective listens on :9090, auto-runs `adb reverse tcp:9090 tcp:9090` so USB devices connect over localhost, and (unless turned off in Settings ▸ Privacy) also accepts devices on your Wi-Fi — the client dials whichever host served the JS bundle. Shows a live timeline of logs, API calls, custom `display()` output, AsyncStorage, and Redux/MST actions. Your app must include and configure the `reactotron-react-native` client.",
        "scrcpy": "Mirrors and controls the device live, in app, through the bundled scrcpy server — click, type, and paste as if your hands were on the phone. The bar below takes screenshots (annotate in place), records without interrupting the mirror, sends nav keys and volume, and pops the mirror out into its own window. Device audio is off by default — the Audio switch in the bar streams it too (restarts the mirror; Android 11+). The mirror follows the device selected in the device bar. Nothing to install.",
        "screenshot": "Captures the screen (`screencap` on Android, `simctl io screenshot` on an iOS Simulator), saves a PNG to ~/Downloads/Droidective, and previews it here. Optional capture delay (to arrange the screen) and auto-copy to the clipboard. Drag the preview anywhere or copy the image.",
        "screen-record": "Records via scrcpy (`--no-playback --record`) on the Mac, so there's no time limit, audio is captured by default (Android 11+), and it survives rotation. Tune max size, bit-rate, FPS, audio, and an optional time limit under Advanced. Stop opens the clip in the editor to trim, rotate, crop, convert, and export. Runs on the bundled scrcpy server — nothing to install.",
        "video-editor": "Loads a recording (or any video you open) into a player and exports edits through ffmpeg: trim with the scrubber handles, rotate/flip, crop, change speed, mute, pick a format (MP4/MOV/MKV/WebM/GIF), and compress. Nothing is written until you Export. Exports run through the bundled ffmpeg — nothing to install.",
        "demo-mode": "Forces a clean status bar (9:41, full battery/Wi-Fi, no notifications) for store screenshots — on Android via the SystemUI demo broadcast, on an iOS Simulator via `simctl status_bar`. Toggle off to restore.",
        "device-info": "Browse the device's hardware/software overview and search every raw getprop value.",
        "root-status": "Probes several independent signals — whether `su -c id` returns uid 0, a `su` binary or Magisk files exist, the build's `ro.build.tags`/`ro.debuggable`/`ro.secure`, and SELinux mode — to judge if the device is rooted. A working root shell is the only definitive proof, and is what Wi-Fi password export and the root-only system tweaks rely on.",
        "simulate": "Simulate device conditions for testing in one place — fake the battery level, flip dark mode and animation scale, override font scale and density, change the locale, toggle Wi-Fi/data/airplane, and set an HTTP proxy. With an iOS Simulator selected it adapts: dark mode, fake battery, demo status bar, and test push notifications. Reset any of them from the overrides pill or the Reset button here.",
        "fake-battery": "Overrides the reported battery level (`dumpsys battery set` on Android, a `simctl status_bar` override on an iOS Simulator) so you can test low-battery UI. Reset from the overrides pill.",
        "dark-mode": "Flips the system-wide dark mode (`cmd uimode night` on Android, `simctl ui appearance` on an iOS Simulator).",
        "push-notification": "Delivers a test APNS payload to an app on a booted iOS Simulator (`simctl push`) — title, body, and an optional badge count. The app must be installed on that simulator; no server or certificates needed.",
        "layout-overrides": "Overrides font scale and display density to test responsive layouts. Reset from the overrides pill.",
        "animation-scale": "Sets all three animation scales to 0× (great for UI tests) or back to 1×.",
        "locale": "Broadcasts a locale change for i18n testing. Best-effort — many ROMs need root for a full switch; apps usually need a restart.",
        "network-toggles": "Flips Wi-Fi, mobile data, and airplane mode via `svc`/`cmd connectivity` — test offline states without touching the device.",
        "http-proxy": "Points the device's global HTTP proxy at Charles/Proxyman/mitmproxy on your Mac. Leave blank and run to clear it.",
        "app-management": "Lifecycle controls for the selected bundle: open, force-stop, background, clear cache (Android 14+), clear data, uninstall.",
        "permissions": "Lists the app's runtime permissions and lets you grant/revoke each — test permission-denied flows instantly.",
        "app-info": "Version, SDK targets, install dates, APK size — and pulls the APK to your Mac.",
        "current-activity": "Shows which Activity is on screen right now (from dumpsys) — useful for navigation debugging and writing deep links.",
        "foreground-package": "Copies the package id of whatever app is currently on screen.",
        "meminfo": "Live PSS memory for the app, refreshed every 2 seconds while it runs.",
        "performance": "Live sampling over adb: per-core CPU (`/proc/stat`), system + per-process RAM (`dumpsys meminfo`), per-process CPU (`dumpsys cpuinfo`), network download/upload speed (`/proc/net/dev`), and the selected app's rendered FPS and jank (`dumpsys gfxinfo`). Record a session and export it as JSON + CSV. Network is device-wide (per-app traffic needs root on modern Android). React Native: gfxinfo measures the native UI frame rate (covering RN's rendered output); the JS-thread FPS isn't exposed over adb — use the in-app Perf Monitor or Flipper for that.",
        "sandbox-browser": "Browses the app's private /data/data files via run-as — debug builds only. Pull databases and prefs to your Mac.",
        "monkey": "Fires N random taps/swipes/keys at the app to shake out crashes. Start small (500).",
        "logcat": "Live log stream. Filter by level, a saved bundle (waits for the app and follows it across restarts), or free text — filters hide non-matching lines; ⌘F finds and steps through matches without hiding anything. Right-click a line to filter by tag, export the buffer to a file.",
        "crash-catcher": "Splits the crash buffer (with a main-buffer fallback) into individual crashes — Java, native, React Native, ANR. Filter by kind/process, watch for new ones, and copy a trace formatted for Slack/Jira.",
        "ios-logs": "Streams the booted simulator's unified log (xcrun simctl spawn <udid> log stream). Scoped to your installed apps by default — Everything is the whole OS, thousands of lines a second. Scrolling up freezes the feed (new lines wait behind the \u{201C}N new\u{201D} pill), levels/process/text narrow what's shown (Info and Debug also widen what the simulator emits), ⌘F finds without hiding lines, and right-clicking a line filters by its process.",
        "bug-report": "Bundles a screenshot, recent logcat, device info, and the selected app's version into one zip in ~/Downloads/Droidective.",
        "terminal": "Real login shells (your $SHELL, PTY-backed via SwiftTerm) inside Droidective. Open as many tabs as you need with + — a new shell starts in the focused shell's directory — rename one with a double-click or right-click, and close it with ×. ⌘D splits the focused pane vertically and ⇧⌘D horizontally (⌘W closes a pane first, then the tab), and the tab list can sit in a sidebar or along the top, Chrome-style. The device selected when a shell opens is exported as ANDROID_SERIAL, so plain adb commands target it without -s — a shell keeps that device for its lifetime, so open a new tab after switching devices. Sessions keep running with scrollback intact while you use other features.",
        "custom-commands": "Your own one-liners with {bundleId} and {serial} placeholders, typed as you'd run them in a terminal. Lines starting with adb are tokenized safely and passed as argv with the selected device's -s injected; anything else (commands, script files) runs through your login shell with its rc file sourced, so aliases and PATH work just like Terminal — use {serial} to target the selected device. Each command chooses where its output goes: silently with the result as a toast, or into a terminal for live output and interactive prompts — the in-app Terminal or your Mac's default terminal app.",
        "file-explorer": "Browse the device's shared storage. Double-click a folder to open it, single-click to select, right-click for options. Copy/cut/paste, delete, create folders, and pull files to your Mac. On a rooted device, flip Root on to browse the whole filesystem from / via su (pulls stage through /data/local/tmp).",
        "apps": "Every installed app (user + system) with search. Select one for its info, live permission toggles, APK pull, and full management — open, restart, force-stop, clear cache (Android 14+) or clear data, disable/enable, and uninstall-for-user/restore (`pm clear` / `pm disable-user` / `pm uninstall --user 0` / `cmd package install-existing`). The reversible per-user actions double as a debloater; removing core system apps can break the UI, so stick to ones you recognise.",
        "install-app": "Install an APK onto the connected device(s) with `adb install -r` — reinstalling keeps the app's data. Drag an `.apk` onto the drop zone or pick one with the file button; with several devices selected it installs on each. Double-clicking an `.apk` in Finder opens Droidective and offers the same install.",
        "apk-studio": "One workspace for a local `.apk`: load it once, then **Inspect** (manifest, permissions, SDK, and signing certificates via `aapt2` + `apksigner`), **Decompile** (`jadx` for readable Java or `apktool` for smali + resources), **Recompile** (rebuild an edited `apktool` tree back into an APK with `apktool b`), and **Sign** the result with `apksigner` (debug key, your own keystore, or a new one created here with `keytool`). jadx, apktool, and a Java runtime are downloaded from their GitHub releases on first use and kept up to date. A typical flow is decompile → edit the files in your editor → recompile → sign → install.",
        "apk-inspector": "Inspects any local `.apk` without installing it: app label, package, version, min/target SDK, the full permission and feature list, and whether it's debuggable — read with the SDK's `aapt2 dump badging`. Signing certificates (scheme v1–v3, subject, SHA-256/SHA-1) come from `apksigner` and need a Java runtime; everything else works without one. Drag an APK in or pick a file.",
        "apk-sign": "Zipaligns and signs an APK with `apksigner` (Android Signature Scheme v1–v3) and verifies the result. Use the embedded debug key (`~/.android/debug.keystore`) for quick local installs, point at your own keystore, or create a new self-signed keystore right here with `keytool` (RSA-2048) — store/key passwords are handed to apksigner/keytool through a private 0600 temp file, never on the command line. The signed copy is written next to the input as `<name>-signed.apk`.",
        "apk-decompile": "Decompiles a local APK and lets you browse the result: **jadx** produces readable Java from the dex, **apktool** disassembles to smali and decodes resources and the manifest. Both run on a Java runtime; jadx and apktool are downloaded from their GitHub releases on first use (and kept up to date), and a Temurin JRE is offered if you don't already have Java. Output is cached locally — pick a file in the tree to view it.",
        "aab-convert": "Converts an Android App Bundle (`.aab`) into a single installable **universal APK** with Google's `bundletool` (`build-apks --mode=universal`) — the store-upload format turned back into something `adb install` accepts. Drop a bundle in or double-click an `.aab` in Finder; the converted APK lands in your capture folder, ready to save elsewhere or install straight onto a device. The Signing row picks the key — your debug keystore (`~/.android/debug.keystore`) by default, an existing release keystore, or a brand-new keystore created in place (passwords are handed over via a private 0600 temp file, never the command line). bundletool ships inside the app; it runs on a detected JDK, with a Temurin runtime offered when you don't have Java.",
        "frida-console": "Prepares a device for Frida dynamic instrumentation. It reads the device architecture and downloads the matching `frida-server` / `frida-gadget` from frida's GitHub releases (kept current). On a **rooted** device it pushes and starts frida-server for you; for **non-rooted** devices it downloads the arch-matched `frida-gadget.so` to inject into a repackaged APK (e.g. `objection patchapk`). You then attach with your own frida client — `frida-ps -U`, `frida -U -n <app>`.",
        "emulators": "Your Android Studio AVDs and Xcode iOS Simulators in one place: launch AVDs normally, cold boot, or wipe data first; boot or shut down simulators. Running ones join the device bar. AVDs need the SDK emulator; simulators need Xcode.",
    ]
}
